services:
  webdav:
    image: nginx:alpine
    build: .
    ports:
      - "80:80"
    volumes:
      - ./webdav/:/var/webdav
    command: [/usr/local/nginx/sbin/nginx, '-g', 'daemon off;']

# Nota de CyberSec A pasta 'webdav' local é propriedade coletiva!
